import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import { SessionProvider } from '@/providers/session';
import { SharedStateContextProvider } from '@/providers/SharedState';
import { NavBar } from '@/components/NavBar';
import FooterComponent from '@/components/FooterComponent';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <SessionProvider>
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased flex flex-col min-h-screen`}
        >
          <SharedStateContextProvider>
            <NavBar />
            <main className="flex-grow z-40">{children}</main>
            <FooterComponent />
          </SharedStateContextProvider>
        </body>
      </SessionProvider>
    </html>
  );
}
